name: Check Release File Update

on:
  release:
    types:
      - created

jobs:
  checkReleaseFileUpdate:
    runs-on: ubuntu-latest

    steps:
      - name: Check Release File Update
        run: |
          # Get the previous release tag
          previous_tag=$(git describe --abbrev=0 --tags ${{ github.event.release.tag_name }}^)

          # Get the list of changed files between the current release and the previous release
          changed_files=$(git diff --name-only $previous_tag ${{ github.event.release.tag_name }})

          # Check if the specific file is in the list of changed files
          if [[ ! $changed_files =~ "./release-notes.md" ]]; then
            echo "The specific file has not been updated. Rejecting the release tag."
            exit 1
          fi
